language: csharp
solution: YTLiveLib.sln
mono: none
dotnet: 2.2
dist: xenial
git:
  depth: false
script:
 - dotnet restore
 - dotnet build
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1